/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dynamsoft_barcode_JBarcode */

#ifndef _Included_com_dynamsoft_barcode_JBarcode
#define _Included_com_dynamsoft_barcode_JBarcode

extern "C" {
/*
 * Class:     com_dynamsoft_barcode_JBarcode
 * Method:    DBR_InitLicense
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dynamsoft_barcode_JBarcode_DBR_1InitLicense
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_dynamsoft_barcode_JBarcode
 * Method:    DBR_DecodeFile
 * Signature: (Ljava/lang/String;IJLcom/dynamsoft/barcode/tagBarcodeResultArray;)I
 */
JNIEXPORT jint JNICALL Java_com_dynamsoft_barcode_JBarcode_DBR_1DecodeFile
  (JNIEnv *, jclass, jstring, jint, jlong, jobject);

/*
 * Class:     com_dynamsoft_barcode_JBarcode
 * Method:    DBR_DecodeFileRect
 * Signature: (Ljava/lang/String;IJIIIILcom/dynamsoft/barcode/tagBarcodeResultArray;)I
 */
JNIEXPORT jint JNICALL Java_com_dynamsoft_barcode_JBarcode_DBR_1DecodeFileRect
  (JNIEnv *, jclass, jstring, jint, jlong, jint, jint, jint, jint, jobject);

/*
 * Class:     com_dynamsoft_barcode_JBarcode
 * Method:    DBR_DecodeBuffer
 * Signature: ([BIIJLcom/dynamsoft/barcode/tagBarcodeResultArray;)I
 */
JNIEXPORT jint JNICALL Java_com_dynamsoft_barcode_JBarcode_DBR_1DecodeBuffer
  (JNIEnv *, jclass, jbyteArray, jint, jint, jlong, jobject);

/*
 * Class:     com_dynamsoft_barcode_JBarcode
 * Method:    DBR_DecodeBufferRect
 * Signature: ([BIIJIIIILcom/dynamsoft/barcode/tagBarcodeResultArray;)I
 */
JNIEXPORT jint JNICALL Java_com_dynamsoft_barcode_JBarcode_DBR_1DecodeBufferRect
  (JNIEnv *, jclass, jbyteArray, jint, jint, jlong, jint, jint, jint, jint, jobject);

/*
 * Class:     com_dynamsoft_barcode_JBarcode
 * Method:    DBR_GetErrorString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dynamsoft_barcode_JBarcode_DBR_1GetErrorString
  (JNIEnv *, jclass, jint);


}
#endif
